# Generated by Django 3.1.2 on 2020-10-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_auto_20201007_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user1',
            options={'verbose_name': '패스트 캠퍼스 사용자', 'verbose_name_plural': '패스트 캠퍼스 사용자'},
        ),
        migrations.AddField(
            model_name='user1',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='password',
            field=models.CharField(max_length=64, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
