# Generated by Django 3.1.2 on 2020-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0002_auto_20201012_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
    ]
